export type FixtureRow = Record<string, unknown>;

/** Generated by scripts/preview/build-fixtures.ts from the public demo dataset. */
export type FixtureData = {
  generatedFor: string;
  tables: Partial<Record<string, FixtureRow[]>>;
};
